### ISSUE TITLE
Update net/zerotier to 1.6.2

### ISSUE THREAD

**Issue by Tennyleaz** [opnsense/ports#107]
Zerotier 1.6.0 (and above) has some major improvements and bugfixs.
[https://github.com/zerotier/ZeroTierOne/releases](https://github.com/zerotier/ZeroTierOne/releases)

Current version of the zerotier port is 1.4.6.
Hope it could be updated.

**Comment by fichtner** [comment]
As soon as FreeBSD port is updated: https://www.freshports.org/net/zerotier/

**Comment by theonemcdonald** [comment]
Soon : https://reviews.freebsd.org/D27415

**Comment by theonemcdonald** [comment]
Boom: https://www.freshports.org/net/zerotier/ 

it is live.

**Comment by fichtner** [comment]
Already pulled in via https://github.com/opnsense/ports/commit/ae96f36e46dd512ea11922b320d8c6614cbd8b70 — thanks a lot ❤️

**Comment by Tennyleaz** [comment]
Plugin seems not updated yet?
I have already manually build 1.6.2 from `opnsense-code` ports though.

**Comment by fichtner** [comment]
Looking at the timestamps and when 20.7.7 was built I mean how could it be?
