### ISSUE TITLE
net/py-netaddr: Update to 0.7.20 or 0.8.0

### ISSUE THREAD

**Issue by vnxme** [opnsense/ports#110]
**Issue:**
OUI database used on ARP/DHCP pages is outdated. See [core/3883](https://github.com/opnsense/core/issues/3883) for details.

**Reason:**
OPNsense 20.7.6 uses py37-netaddr 0.7.19 which contains an outdated OUI database.

**Solution:**
Is it possible to update [net/py-netaddr](https://github.com/opnsense/ports/tree/master/net/py-netaddr) to 0.7.20 or even to 0.8.0 [release](https://github.com/netaddr/netaddr/releases)?

**Comment by fichtner** [comment]
Basically we are still here waiting for the ports update.

https://forum.opnsense.org/index.php?topic=10380.msg88538#msg88538

**Comment by vnxme** [comment]
@fichtner Thank you for pushing the package maintainer! Now it seems to be fixed.

**Comment by fichtner** [comment]
Great teamwork, thanks again!
