### ISSUE TITLE
net/igmpproxy: Update IGMP Proxy to 0.3

### ISSUE THREAD

**Issue by johnkeates** [opnsense/ports#120]
An updated version of the IGMP Proxy was released and provides a few updates to the downstream hash table as well as some FreeBSD build updates.

I'd be happy to make a PR if that's not owned by someone else (once I find the correct place where the upstream gets referred).

If the version of the package is not related to the plugin at all (i.e. because the plugin simply depends on the package being available as a port), this is obviously a redundant issue and I'll have to do some homework to figure out how the upstream-to-port stream works.

**Comment by johnkeates** [comment]
@fichtner thanks! This place makes a lot more sense than the plugins repo.

**Comment by fichtner** [comment]
@johnkeates thanks, I missed the release. The update is relatively trivial: https://github.com/opnsense/ports/commit/d3d02e7e235a3027136f2175c3ab8ab8ec40b4fb

I can publish a test package in a bit...

**Comment by fichtner** [comment]
# pkg add -f https://pkg.opnsense.org/FreeBSD:12:amd64/20.7/misc/igmpproxy-0.3,1.txz

Let me know how that works. :)

**Comment by johnkeates** [comment]
So far so good! I'll keep it at that version and if something breaks I'll let you know.

**Comment by johnkeates** [comment]
Still working great!

**Comment by fichtner** [comment]
Ok nice, we will add it to FreeBSD ports and 21.1 eventually.


Cheers,
Franco
