### ISSUE TITLE
Push 15.7.11 Tag

### ISSUE THREAD

**Issue by lattera** [opnsense/ports#13]
Looks like this was forgotten. Thanks!

**Comment by fichtner** [comment]
Shawn, there's no 15.7.11 for ports, it's the same as 15.7.10. Unfortunately, git tags are very annoying in this regard, trying to tag the same commit.

There's a checkout script that tries to do fuzzy matching in tools.git:

    # make checkout VERSION=15.7.11

Does this work for you?

**Comment by lattera** [comment]
Not really. I need the commit that ports.git was at when you built the 15.7.11 images. My version numbers are off from yours in my tools.git, so the fuzzy matching's going to fail. For example, my version number is 15.7-hbsd-exp-06. Without knowing which commit ports.git was on when you built the images, I can't build mine, especially with the os-update -> opnsense-update rename.

**Comment by fichtner** [comment]
If a tag was not there, it was the one before. I can't forward ports when I haven't updated them. The same happens with base/kernel. :/

**Comment by lattera** [comment]
Well, can you at least tell me what commit ports.git was on when you built the 15.7.11 images? Otherwise, I'm dead in the water and have no way to go forward with 15.7 at all.

**Comment by fichtner** [comment]
Well well, I remember being naughty doing that rename manually.

**Comment by fichtner** [comment]
I've tagged the rename. It is most likely fine. https://github.com/opnsense/ports/releases/tag/15.7.11

**Comment by fichtner** [comment]
Jesus, sorry, tag is back in a second.

**Comment by lattera** [comment]
Cool. I'm hoping that will allow me to build with core and tools at 15.7.11. I'll give that a try at vbsdcon and let you know. If everything succeeds, then I'll close the ticket. Leaving it open for now.

**Comment by fichtner** [comment]
Tag is correct now. Looking forward to your feedback. :)

**Comment by fichtner** [comment]
Just to explain the naughty bits: images we did in 15.7.11 and I desperately wanted them to have the rename so I fiddled it in. Sorry about that.

**Comment by lattera** [comment]
No worries. Maybe we could post on a mailing list a "HEADS UP" in the future for breaking changes like this that cause incongruencies with stable branches.

**Comment by fichtner** [comment]
Good idea, that devel@ list could use a breath of fresh air.
