### ISSUE TITLE
stages.py Failed to rename devices: Unexpected error while running command. Command [`ip`, `-6`, `addr`,`show`, `permanent`, `scope`,`global`]

### ISSUE THREAD

**Issue by Ks89** [opnsense/ports#134]
I installed `pkg install net/cloud-init` then if I run `cloud-init init ` I receive this error:

```
stages.py[WARNING]: Failed to rename devices: Unexpected error while running command.
Command [`ip`, `-6`, `addr`,`show`, `permanent`, `scope`,`global`]
Exit code: -
Reason: [Errno 2] No such file or directory: b`ip`
Stdout: -
Stderr: -
No `init` modules to run under section `cloud_init_modules`
```

It seems that there is a missing patch file to remove also that `ip` command.
@fichtner I saw that you are the author of this port. Do you have suggestions how to fix that?

I started the same discussion with a full description of the problem in both [opnsense forum](https://forum.opnsense.org/index.php?topic=24941.0) and [unix.stackexchange](https://unix.stackexchange.com/questions/672292/how-can-i-use-cloud-init-nocloud-with-opnsense-21)

**Comment by fichtner** [comment]
Not the author and FreeBSD ports issue if at all. Closing.
