### ISSUE TITLE
DnsDist compiles but crashes with a core dump and "Bus Error" when run

### ISSUE THREAD

**Issue by ysguy** [opnsense/ports#139]
details:

uname-r: 13.0-STABLE

Type | opnsense |  
  | Version | 22.1 |  
  | Architecture | amd64 |  
  | Flavour | OpenSSL |  
  | Commit | 6c9017057 |  
  | Mirror | http://mirror.wdc1.us.leaseweb.net/opnsense/FreeBSD:13:amd64/22.1 |  
  | Repositories | OPNsense, SunnyValley |  
  | Updated on | Thu Jan 27 22:15:54 MST 2022 |  

compiled via CLI in the /usr/ports/dns/dnsdist folder with a make deinstall then a make install

dnsdist --version works, but launching with any parameters or just dnsdist crashes with error "Bus Error" 

distinfo file contents:
TIMESTAMP = 1631700092
SHA256 (dnsdist-1.6.1.tar.bz2) = 29040a43982ae1ad5b7313f081e26519ab3a58af6bced438311da3a65370a3a5
SIZE (dnsdist-1.6.1.tar.bz2) = 1328069

i did try and git clone the powerdns git and then go into the dnsdistdist folder and compile, complains about a file missing and ragel not installed, cannot compile ragel as it errors out (i gave up as well).

**Comment by fichtner** [comment]
I think you should take this up with https://bugs.FreeBSD.org we don’t even use this port.
