### ISSUE TITLE
Requesting Addition of ocserv

### ISSUE THREAD

**Issue by sempervictus** [opnsense/ports#140]
Cisco's AnyConnect remains one of the reasons why people still deploy ASAs, and it would be great to use OPNSense to replace that function (along with the devices which currently service it). There's is a [BSD port](http://ports.su/net/ocserv) of ocserv which is an OpenConnect server compatible with the AnyConnect clients deployed on so many work laptops. If this could be brought into OPNSense and given a plugin wrapper, it could help move companies away from that vestigial mess who are still stuck with it because their endpoints have the client and its written in their corporate policy that they use the technology for VPN.

**Comment by fichtner** [comment]
Still out of scope for us.
