### ISSUE TITLE
net/samba413: py38-dnspython-2.1.0 conflicts with py38-dnspython2-2.2.0

### ISSUE THREAD

**Issue by rmundel** [opnsense/ports#141]
Hey guys, I'm trying to build the net/samba413 following the docs on how to make install the [ports tree](https://docs.opnsense.org/manual/software_included.html?highlight=ports#the-ports-tree) and i'm getting stopped by some conflict with dnspython and dnspython2.
![image](https://user-images.githubusercontent.com/13142574/155073304-4510318a-cb7e-4f92-a649-058d6ad755c9.png)

Any thoughs on how to fix this?

**Comment by fichtner** [comment]
@rmundel hi, there is no way to install dnspython and dnspython2 alongside each other. The core requires version 2 so a proper fix would be to have samba use dnspython2 too. Maybe a newer version can support it? Maybe the FreeBSD port is simply not up to date?

**Comment by rmundel** [comment]
@fichtner The latest version I could find for FreeBSD is [net/samba413](https://www.freshports.org/net/samba413/), which requires py38-dnspython>=1.15.0 as runtime dependecy.
--
Just looked in the [Samba Wiki](https://wiki.samba.org/index.php/Package_Dependencies_Required_to_Build_Samba) and searched for python3-dnspython in the Ubuntu 18.04 and 20.04 repositories, both returned v1.15/1.16.

**Comment by fichtner** [comment]
this sounds promising... https://bugzilla.samba.org/show_bug.cgi?id=14553

**Comment by rmundel** [comment]
Well, just found out that it was already fixed in the 4.13.1. I'm way out of my league now, but I'll try to build samba413 again.
On question though, when I make some port package, it automatically chooses the latest version for me? Maybe I'm building the 4.13.0.

**Comment by fichtner** [comment]
No worries, you are doing good :) The latest version seems to be:

https://github.com/opnsense/ports/blob/26bcf2fc63b502497a22a8cd311052b6296be658/net/samba413/Makefile#L25

I suppose the only thing you need to change is:

https://github.com/opnsense/ports/blob/26bcf2fc63b502497a22a8cd311052b6296be658/net/samba413/Makefile#L469

Into something like:

`${PYTHON_PKGNAMEPREFIX}dnspython2>=2.0.0:dns/py-dnspython2@${PY_FLAVOR}`

**Comment by rmundel** [comment]
I'll test it out. If works, maybe I can try to make some PR in the opnsense/ports.
BRB

**Comment by rmundel** [comment]
Bump! @fichtner 😃

**Comment by fichtner** [comment]
@rmundel I saw freebsd deprecating dns/py-dnspython so I think we should try our luck there?

**Comment by fichtner** [comment]
Well I see it here https://github.com/opnsense/ports/tree/master/net/samba413 but I meant that the one-line diff should be published at https://bugs.freebsd.org instead. it is very likely being picked up.

**Comment by fichtner** [comment]
@rmundel thanks, please let me know the link so I can CC and prod if it is stalled (not a committer there myself but we can always push for a committer via mailing list).

**Comment by rmundel** [comment]
I don't think I made a great job trying to persuade the FreeBSD guys to accept my suggestion (Why would they bother changing that for our use? lol), but here it is: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=262469

**Comment by fichtner** [comment]
@rmundel sorry about all this.. we need to wait for 22.1.3 to hit including https://github.com/opnsense/core/commit/b5619fef39 and https://github.com/opnsense/tools/commit/7aacc619b2c

unfortunately it will break your interim build as well as some other things in our ecosystem so yay. at least we can consider this solved. close? :)

**Comment by rmundel** [comment]
Thansk for all the help with this.
I can redo my build just fine!
I'll close this and wait for 22.1.3 than! do you guys have and ETA for it?

**Comment by fichtner** [comment]
Tentatively I would say middle of next week, but since this is my first day back after a week away that I don't have a good grasp of what else needs to be in 22.1.3 from the ports side of things especially. Of course, I also need to double check that the rename doesn't cause any issues on upgrades beforehand, but I think it will be ok. :)

**Comment by rmundel** [comment]
Ok! I'll schedule my work on this again when it's releases. Thanks.
