### ISSUE TITLE
Re the DHCP server for IPv4

### ISSUE THREAD

**Issue by seamusdemora** [opnsense/ports#148]
Hello,

I am a user of OPNsense - and a big fan! I have been puzzling over a question: Why does the DHCP server in OPNsense not create an entry in its lease table for a DHCP client that uses the INFORM option? I know the INFORM option is supported in your DHCP server because I have used it, and it works. However, not having an entry in the lease table makes it difficult to manage my static address pool. 

I had hoped to find a source code repository for DHCP server here, suspecting it was a FreeBSD port. I still suspect the sources may be housed here, but I only found the IPv6 DHCP server - not what I'm interested in at the moment. I would appreciate it if someone could point me toward the DHCP server source - actually that would answer my question completely :)

**Comment by fichtner** [comment]
Not part of our scope and issue is stale already (> 1 year)
