### ISSUE TITLE
Please pull patched gdb version from freebsd repo for aarch64 compilation

### ISSUE THREAD

**Issue by JohannesNeu** [opnsense/ports#149]
Hi,
I am having trouble compiling opnsense for arm64 due to a bug in gdb. The guys at freebsd were so nice to fix it and patched gdb.
I did most of my testing with the icinga2 port because this is the port I encountered the error with.
Can you please pull a newer version from the freebsd repo as I am able to compile icinga2 without a problem using freebsd, but not with the opnsense build tools?
This is the bug ticket I filed: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=264095
And this is the patch: https://cgit.freebsd.org/ports/commit/?id=c5722abb6a5cfdb83d8e2fcce271cba48dbd7281

There is some history to my tries:
https://github.com/opnsense/tools/issues/290
https://github.com/opnsense/tools/issues/295

**Comment by mimugmail** [comment]
No need for an extra ticket. It will get merged with the next pull, those are usually done once a week, just be a bit patient :)
