### ISSUE TITLE
dns/dnscrypt-proxy2 is out of sync with FreeBSD

### ISSUE THREAD

**Issue by L1ghtn1ng** [opnsense/ports#165]
dns/dnscrypt-proxy2 is out of sync with FreeBSD, here is the latest port version [2.1.2_4](https://stage.freshports.org/dns/dnscrypt-proxy2/#history) that is available compared to what is in OPNsense(2.0.45)

**Comment by fichtner** [comment]
Yes, because the plugin is not ready.

**Comment by bcookatpcsd** [comment]
Can this not be done? Even if it's just updating the binary and not all the new configuration options?

**Comment by fichtner** [comment]
I‘m not against it but I also don’t intend to do more than providing the port update for the person that does it. CC @mimugmail  although he’s probably also busy.
