### ISSUE TITLE
How to build only gkrellmd from gkrellm2

### ISSUE THREAD

**Issue by fuzzyeric** [opnsense/ports#167]
Building gkrellm (on DEC740 https://shop.opnsense.com/product/dec740-opnsense-desktop-security-appliance/?PageSpeed=noscript , running OPNsense 22.7.10_2-amd64 on FreeBSD 13.1-RELEASE-p5 )
    > sudo opnsense-code ports
    > cd /usr/ports/sysutils/gkrellm2
    > sudo make install
    # ...
    # spends much time clearly building packages for the client, useless for a headless device
    # ...
    ===>  Configuring for gtk2-2.24.33
    gtk2-2.24.33: Needs cairo with X11 support enabled.
    *** Error code 1
    
    Stop.
    make[1]: stopped in /usr/ports/x11-toolkits/gtk20
    *** Error code 1

    Stop.
    make: stopped in /usr/ports/sysutils/gkrellm2

... which is fine, I guess, because the client is useless here.  However, I can't seem to find a make target that will build and install gkrellmd, which *is* useful on this device.

(Now if I could just figure out how to clear out the 100s MB of X/gnome/gtk junk that was downloaded and built...)

Request documentation, perhaps in file "pkg-descr" and/or in the Makefile itself, for make targets for the client, the server, and both; the installation of each of those three; and the docs for each of those three (or whatever subset of the three is sensible).

Alternatively, request documentation (in either/both of the above files) for how to modify the Makefile to only build and install the server component (and its docs, if there are any).

**Comment by fichtner** [comment]
So we do disable X11 in /etc/make.conf (created using` opnsense-code ports` run). The question whether X11 can be disabled in the FreeBSD ports or that the software will actually run without it is not in the scope of our project. You'll have a bit more luck over at https://bugs.freebsd.org although as mentioned it could also be an upstream requirement.

We do not recommend enabling X11. It will definitely bloat the install and may cause package incompatibilities for your future updates through our firmware.


Cheers,
Franco
