### ISSUE TITLE
Request to add salt

### ISSUE THREAD

**Issue by monkz** [opnsense/ports#169]
Hi @fichtner ,

I want to tinker with salt (analog to puppet) to centralize the configuration.
May you add it in the repositories?
Maybe it is possible to adapt the plugin for puppet for salt.

https://cgit.freebsd.org/ports/tree/sysutils/py-salt

Salt : Remote Execution and State Manager
======================================

Salt is a powerful remote execution and state manager that can be
used to administer servers in a fast and efficient way.

See also: https://saltproject.io/

**Comment by monkz** [comment]
Found https://forum.opnsense.org/index.php?topic=5157.0 so I will close it for now

**Comment by fichtner** [comment]
@monkz sorry a bit late to the party. can you let me know how your experiment goes? I'd like to know if the stack is still heavy or not. Inclusion is possible under certain constraints as discussed there in the past.


Thanks,
Franco

**Comment by monkz** [comment]
No need to say sorry - and sure I'll report on my experiment.

Regarding your question of "heavy" - It might still be, i've no comparison to your former assessment.

All in all my experiment has just the goal to basically "get the foot in the door", to enable further development, to allow companies that use predominantly salt for configuration management to have a argument for choosing opnsense. Same argument applies to APM Stacks.

Than again your question regarding "heavy" dependencies - may everyone choose their own poison. (But I've to agree, that it puts strain on the compile and storage side - and you made a valid argument about the ecological footprint)

**Comment by monkz** [comment]
@fichtner 
Current status of my experiment:
https://github.com/opnsense/plugins/pull/3350

This is currently completely untested - but should have all significant changes at least "hinted"

**Comment by monkz** [comment]
Yup still heavy. I understand your comment now. We'll see what the future holds 😅

**Comment by fichtner** [comment]
@monkz if you have updates/news in that regrade let me know and we can reevaluate
