### ISSUE TITLE
Tailscale requires missing go120

### ISSUE THREAD

**Issue by kensel** [opnsense/ports#175]
OPNsense 23.1.11 just confirmed fully up to date and ran opnsense-code ports to install Tailscale per the sites [1](https://www.wundertech.net/how-to-set-up-tailscale-on-opnsense/), [2](https://tailscale.com/kb/1097/install-opnsense/).  I get the following error and haven't been able to find a port or pkg that provides go120.  I tried adding the pkg os-wiregaurd-go but didn't make a difference to Tailscale install.

```
root@rtr2:/usr/ports/security/tailscale # make install
===>  License BSD3CLAUSE accepted by the user
===>   tailscale-1.44.0 depends on file: /usr/local/sbin/pkg - found
===>   tailscale-1.44.0 depends on file: /usr/local/bin/go120 - not found
===>   tailscale-1.44.0 depends on file: /usr/local/bin/go120 - not found
*** Error code 1

Stop.
make: stopped in /usr/ports/security/tailscale
```

**Comment by fichtner** [comment]
You probably have an unclean build env. The ports tree needs a proper reset for leftover build artefacts. go120 will be provided when needed.
