### ISSUE TITLE
Tailscale version mismatch

### ISSUE THREAD

**Issue by teklabania** [opnsense/ports#180]
When installing tailscale from ports I see in the command output that 1.52.1 version is being installed. But I noticed that in Tailscale Admin Console 1.42.0 version is reported. I checked that in command line and indeed the binary states it's 1.42.0.

I tried `make deinstall`, pulled latest ports and `make install` again with no success:

```
# /usr/ports/security/tailscale]# make install
===>  Installing for tailscale-1.52.1
===>  Checking if tailscale is already installed
===>   Registering installation for tailscale-1.52.1
Installing tailscale-1.52.1...

# tailscale --version
1.42.0
  go version: go1.20.3
```

**Comment by fichtner** [comment]
We don’t currently support tailscale so all we do is provide the port as FreeBSD provides it. Maybe you have more luck over at https://bugs.freebsd.org

**Comment by teklabania** [comment]
Cleaning all artifacts from `/usr/obj/` and re-building again ends up with a correct version:
```
# tailscale --version
1.52.1
  go version: go1.21.1
```

**Comment by fichtner** [comment]
I’d expect „make clean“ to fix that too in between builds. Did you build it multiple times over the last weeks or months?

**Comment by teklabania** [comment]
I installed tailscale a few months ago (approx 3 months). Lately I noticed it's out of date, so I just checked out the latest ports and run `make install`. But version didn't change. Then I run `make deinstall` and `make install`.
