### ISSUE TITLE
GNU Wget2 is the successor of GNU Wget

### ISSUE THREAD

**Issue by ronin3510** [opnsense/ports#185]
Hi guys,

I've recently found out about wget2 and decided to have a quick look.

> GNU Wget2 is the successor of GNU Wget, a file and recursive website
downloader.
>
> Designed and written from scratch it wraps around libwget, that
provides the basic functions needed by a web client.
>
> Wget2 works multi-threaded and uses many features to allow fast
operation.
>
> In many cases Wget2 downloads much faster than Wget1.x due to HTTP2,
HTTP compression, parallel connections and use of If-Modified-Since
HTTP header.

On FreeBSD 14 there are two dependencies.

`New packages to be INSTALLED:
libhsts: 0.1.0
libmicrohttpd: 0.9.77
wget2: 2.1.0`

I'm no sure what depends on/requires wget in OPNsense so I'm opening this issue for you to evaluate whether moving to wget2 is a possibility.

Thank you. 

[https://www.freshports.org/www/wget2/](url)
[https://www.phoronix.com/news/Fedora-40-Security-Improvements](url)

**Comment by fichtner** [comment]
@ronin3510 I don't mind adding it to the ports.conf in tools, but I'd appreciate the PR. Closing this to avoid clutter because the ports side looks done.
