### ISSUE TITLE
SSLH Update to v2.1.2

### ISSUE THREAD

**Issue by efaden** [opnsense/ports#194]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
Feature, or rather a plugin version update.  The latest version of sslh has a vulnerability fix as well as allowing UDP now.

**Describe the solution you'd like**
Update sslh to version 2.1.2

**Describe alternatives you've considered**
Using sslh on another machine and using a port forward.

**Additional context**

**Comment by fichtner** [comment]
We're just following the FreeBSD ports. If anyone wants to prod there be my guest.

**Comment by doktornotor** [comment]
Looks like it's already there, can be closed. 😉 

```
 # pkg install sslh
Updating OPNsense repository catalogue...
OPNsense repository is up to date.
All repositories are up to date.
The following 3 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
        libconfig: 1.7.3 [OPNsense]
        libev: 4.33_1,1 [OPNsense]
        sslh: 2.1.2 [OPNsense]

Number of packages to be installed: 3

The process will require 1 MiB more space.
289 KiB to be downloaded.
```
