### ISSUE TITLE
The pcre library in use is currently deprecated.

### ISSUE THREAD

**Issue by Zerophase** [opnsense/ports#196]
Currently, when installing Shadowsocks it complains about version 8.45_4 of pcre as being deprecated. It tells you to use devel/pcre2. Might want to prepare for upgrading it.

opnsense/plugins#4001

**Comment by AdSchellevis** [comment]
@Zerophase upstream is FreeBSD ports (https://github.com/freebsd/freebsd-ports/tree/main/net/shadowsocks-libev), their bug tracker is available at https://bugs.freebsd.org/bugzilla/ (https://www.freebsd.org/support/bugreports/)
