### ISSUE TITLE
[24.7.10] avahi fails to install, intltool not/won't install, invalid perl5 version

### ISSUE THREAD

**Issue by arichtman** [opnsense/ports#211]
## What am I trying to do?

After the 24.7.10 update I found `avahi-daemon` and `avahi-dnsconfd` missing. 
Re-install Avahi and the daemon to enable mTLS responses (and resolution).

## What am I expecting?

Avahi installs.

## Steps to reproduce

```
curl https://raw.githubusercontent.com/opnsense/tools/refs/heads/master/config/24.7/make.conf -o /etc/make.conf
git clone https://github.com/opnsense/ports.git /usr/ports
cd /usr/ports
git checkout 24.7.10
cd net/avahi
make
```

FWIW if I remove `/etc/make.conf` it succeeds

## Diagnostics/details

Errors:

- `avahi-app-0.8_2 depends on file: /usr/local/bin/intltool-extract - not found`
- `intltool-0.51.0_2 Invalid perl5 version %%PERL%%`

![image](https://github.com/user-attachments/assets/903247d6-ba51-436d-bb72-87f590cc0d48)

```
# uname -a
FreeBSD opnsense.internal 14.1-RELEASE-p6 FreeBSD 14.1-RELEASE-p6 stable/24.7-n267981-8375762712f SMP amd64
```

## References

- [OPNsense forum on port installation](https://forum.opnsense.org/index.php?topic=2004)

**Comment by fichtner** [comment]
# opnsense-code ports && cd /usr/ports/net/avahi && make clean all reinstall

“reinstall” may not work if not already installed, then “install” does the trick.

**Comment by fichtner** [comment]
I made a note in the thread about the outdated instructions and also linked https://docs.opnsense.org/manual/software_included.html#the-ports-tree

Going to close this as it looks solved. Thanks for the heads-up! :)
