### ISSUE TITLE
net/ntopng: switch rrdtool dependency to unbreak build

### ISSUE THREAD

**Issue by dimangelid** [opnsense/ports#27]
Hello, i'm trying to install ntopng port.
I cloned the ports repo, i have installed all the required packages and i try to install ntopng with make install. The installation never completes and i get the following output. I'm running a fully updated Opnsense 16.7.5

===>  Building for ntopng-2.4
gmake[2]: Entering directory '/usr/ports/net/ntopng/work/ntopng-2.4'
/usr/bin/clang++ -Wall -I/usr/ports/net/ntopng/work/ntopng-2.4 -I/usr/ports/net/ntopng/work/ntopng-2.4/include -g -Wall -I/usr/ports/net/ntopng/work/ntopng-2.4 -I/usr/ports/net/ntopng/work/ntopng-2.4/include -I /usr/ports/net/ntopng/work/ntopng-2.4/third-party/hiredis -I/usr/ports/net/ntopng/work/ntopng-2.4/third-party/mongoose -I/usr/local/include/json-c   -I/usr/local/include/libndpi-1.8.0/libndpi   -I/usr/local/include/luajit-2.0   -I/opt/rrdtool-1.4.8/include   -I/usr/local/include   -I/usr/local/include/mysql -isystem /usr/local/include -I/usr/ports/net/ntopng/work/ntopng-2.4 -I/usr/ports/net/ntopng/work/ntopng-2.4/include -I/usr/ports/net/ntopng/work/ntopng-2.4/third-party/http-client-c/src/  -DDATA_DIR='"/usr/local/share"' -I/usr/ports/net/ntopng/work/ntopng-2.4/third-party/libgeohash -I/usr/ports/net/ntopng/work/ntopng-2.4/third-party/patricia  -O2 -pipe -fstack-protector -isystem /usr/local/include -fno-strict-aliasing  -isystem /usr/local/include -c src/Lua.cpp -o src/Lua.o
src/Lua.cpp:2223:3: error: unknown type name 'rrd_time_value_t'; did you mean 'rrd_time_value'?
  rrd_time_value_t start_tv, end_tv;
  ^~~~~~~~~~~~~~~~
  rrd_time_value
/usr/local/include/rrd.h:109:8: note: 'rrd_time_value' declared here
struct rrd_time_value {
       ^
src/Lua.cpp:2242:15: error: use of undeclared identifier 'rrd_parsetime'; did you mean 'parsetime'?
    if((err = rrd_parsetime(start_s, &start_tv)) != NULL) {
              ^~~~~~~~~~~~~
              parsetime
/usr/local/include/rrd.h:115:7: note: 'parsetime' declared here
char _parsetime(const char *spec, struct rrd_time_value *ptv);
      ^
src/Lua.cpp:2250:15: error: use of undeclared identifier 'rrd_parsetime'; did you mean 'parsetime'?
    if((err = rrd_parsetime(end_s, &end_tv)) != NULL) {
              ^~~~~~~~~~~~~
              parsetime
/usr/local/include/rrd.h:115:7: note: 'parsetime' declared here
char *parsetime(const char *spec, struct rrd_time_value *ptv);
      ^
src/Lua.cpp:2255:8: error: use of undeclared identifier 'rrd_proc_start_end'; did you mean 'proc_start_end'?
    if(rrd_proc_start_end(&start_tv, &end_tv, &start, &end) == -1)
       ^~~~~~~~~~~~~~~~~~
       proc_start_end
/usr/local/include/rrd.h:129:5: note: 'proc_start_end' declared here
int proc_start_end (struct rrd_time_value *,  struct rrd_time_value *, time_t *, time_t *);
    ^
src/Lua.cpp:2286:5: error: use of undeclared identifier 'rrd_freemem'
    rrd_freemem(names[i]);
    ^
src/Lua.cpp:2288:3: error: use of undeclared identifier 'rrd_freemem'
  rrd_freemem(names);
  ^
src/Lua.cpp:2298:19: error: use of undeclared identifier 'DNAN'
      if(value != DNAN /_ Skip NaN _/) {
                  ^
src/Lua.cpp:2306:3: error: use of undeclared identifier 'rrd_freemem'
  rrd_freemem(data);
  ^
8 errors generated.
gmake[2]: *_\* [Makefile:67: src/Lua.o] Error 1
gmake[2]: Leaving directory '/usr/ports/net/ntopng/work/ntopng-2.4'
===> Compilation failed unexpectedly.
Try to set MAKE_JOBS_UNSAFE=yes and rebuild before reporting the failure to
the maintainer.
**\* Error code 1

Stop.
make[1]: stopped in /usr/ports/net/ntopng
**\* Error code 1

Stop.
make: stopped in /usr/ports/net/ntopng

**Comment by fichtner** [comment]
Hi there,

It looks like the build clashes with our older rrdtool version. I will take a look...


Cheers,
Franco

**Comment by fichtner** [comment]
ntopng depends on databases/rrdtool, which is version 1.6, but we still use databases/rrdtool12, which is 1.2. I can see how easy a migration is, but it's not a quick fix...

**Comment by fichtner** [comment]
I gave the health graphs a test run on databases/rrdtool and they disappeared, which means we need to take care of migration...

I will try to get this into 17.1, but for now our road map has way higher priorities than this.

https://opnsense.org/about/road-map/


Cheers,
Franco

**Comment by dimangelid** [comment]
Hello and thank you for your answer! ntopng is one of the things that i miss from pfsense and it is not so easy to take the decision to use opnsense. 
Is there any workaround to install ntopng? Or any possibility to install it on a remote machine and connect to opnsense in order to take the statistics?

**Comment by fichtner** [comment]
I could try to treat rrdtool as a build dependency, if you don't use ntopng's rrd capabilities. If you let me know what arch/crypto you want to use I will provide a test package (e.g. amd64/LibreSSL).

**Comment by AdSchellevis** [comment]
@dimangelid Do you know OPNsense has network statistics included with network insight?

**Comment by dimangelid** [comment]
@fichtner Currently i'm not using the rrd capabilities. I'm using amd64/OpenSSL

@AdSchellevis Yes, i have seen them. But they can't be compared with ntopng. ntopng is very detailed and you can see almost every activity on your network

**Comment by fichtner** [comment]
Fixed.
