### ISSUE TITLE
Feature Request: Build NGINX with NAXSI

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/ports#28]
build nginx with https://github.com/nbs-system/naxsi to have a waf on OPNsense

**Comment by fabianfrz** [comment]
It seems to be available as an option:
https://github.com/opnsense/ports/blob/master/www/nginx/Makefile#L112

**Comment by fichtner** [comment]
Closed with https://github.com/opnsense/tools/commit/4fa23ef3d889bcf721be79329914719ba7dfc18d

**Comment by fabianfrz** [comment]
thanks - now it is possible to have a web application firewall on opnsense
