### ISSUE TITLE
net/haproxy: test and merge update to 1.7

### ISSUE THREAD

**Issue by fraenki** [opnsense/ports#30]
HAProxy was just recently updated to version 1.7.1 in the FreeBSD ports tree. It's a new major release. We should stay on version 1.6.x for OPNsense 16.7/17.1 and only ship HAProxy 1.7.x with OPNsense 17.7.

**Comment by fichtner** [comment]
I was waiting for your input on this. :) We can only have one version *but I can offer a test build for 1.7.1 -- for FreeBSD 10.3 or FreeBSD 11.0?

**Comment by fraenki** [comment]
FreeBSD 11 would be my choice :)

**Comment by fichtner** [comment]
does not even build :D

**Comment by fichtner** [comment]
ok, just LUA, fixed https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=215444

**Comment by fichtner** [comment]
If you set your firmware flavour to "(other)" and type the following you will be able to upgrade to the latest snapshot including your 1.8 HAProxy changes:

    17.1/experimental

**Comment by fraenki** [comment]
@fichtner, I think we should ship HAProxy 1.7 with OPNsense 17.7. I did some quick tests and haven't noticed any regression. I'll do more in-depth testing on 17.7 alpha/beta/rc.

**Comment by fichtner** [comment]
I'll pull in 1.7.7 when I create the trampoline branch for 17.7. In the current planning there will only be 1-2 RCs
