### ISSUE TITLE
update the chef solo port

### ISSUE THREAD

**Issue by EugenMayer** [opnsense/ports#34]
According to the chef freebsd client maintainer the current build is pretty outdated and will cause issues. 

I asked martinisoft if he would be open minded to assist if we have questions and he told me, he tries.

What are the particular todos on this @fichtner ?

**Comment by EugenMayer** [comment]
Got told that looking at how the omnibos packages are build https://github.com/chef/chef/tree/master/omnibus would be a good guide on this

**Comment by fichtner** [comment]
Needs to be handled via https://bugs.freebsd.org/bugzilla/
