### ISSUE TITLE
[BUG] quagga fails to start probably because of a failed system call

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/ports#39]
truss gives this as the last call: setregid(0x65,0x65)
after this, only exit happens.

ospfd can run via with `--user root --group wheel` - so I think it is failing because of being unable to switch the user to `quagga` also known as `0x65`. Sometimes it works after a reinstall but not after the next reboot / restart.

The user and the group exist on the system. The return code (`$?`) is 1

Version: 17.1.2

**Comment by fichtner** [comment]
this was done, right?

**Comment by fabianfrz** [comment]
yes it was ;)
