### ISSUE TITLE
enable zabbix-proxy with sqlite

### ISSUE THREAD

**Issue by ra1nb0w** [opnsense/ports#42]
Hello,
what do you think if you enable zabbix-proxy with sqlite support (avoid mysql/psql) on opnsense?
I mean, only as build/package like zabbix-agent and without interface.

thanks for all your work!

**Comment by fichtner** [comment]
Hi @ra1nb0w,

Sure, done: https://github.com/opnsense/tools/commit/9cb59ab97481f287657c440bb25d20ac6e170c9d

Package will be available in 17.1.8. :)


Cheers,
Franco

**Comment by ra1nb0w** [comment]
thanks a lot!
