### ISSUE TITLE
pkg for clamav

### ISSUE THREAD

**Issue by mimugmail** [opnsense/ports#44]
Hi @fichtner 

How about building a pkg for clamav as we spoked last time? :)

**Comment by fichtner** [comment]
sure, will be in 17.7.1 :)

**Comment by mimugmail** [comment]
<3

I did some research in squidclamav and c-icap.
We can use squidclamav or c-icap-modules, but this port fails with:

root@OPNsense:/usr/ports/www/c-icap-modules # make install
===>  Installing for c-icap-modules-0.4.5
===>   c-icap-modules-0.4.5 depends on shared library: libicapapi.so - found (/usr/local/lib/libicapapi.so)
===>   c-icap-modules-0.4.5 depends on shared library: libclamav.so - found (/usr/local/lib/libclamav.so)
===>  Checking if c-icap-modules already installed
===>   Registering installation for c-icap-modules-0.4.5
pkg-static: Unable to access file /usr/obj/usr/ports/www/c-icap-modules/work/stage/usr/local/etc/c-icap/clamav_mod.conf.default:No such file or directory
pkg-static: Unable to access file /usr/obj/usr/ports/www/c-icap-modules/work/stage/usr/local/lib/c_icap/clamav_mod.a:No such file or directory
pkg-static: Unable to access file /usr/obj/usr/ports/www/c-icap-modules/work/stage/usr/local/lib/c_icap/clamav_mod.so:No such file or directory
*** Error code 74

Stop.
make: stopped in /usr/ports/www/c-icap-modules
