### ISSUE TITLE
net/haproxy: 1.7.9

### ISSUE THREAD

**Issue by fichtner** [opnsense/ports#45]
I've committed 1.7.9 to the ports tree to run a nightly build and provide a package. Please advise if to stay on 1.7.8 for 17.7.1 or move to the newer version. Reverting is not an issue, I just pushed it in to do an automatic QA build. :)

**Comment by fichtner** [comment]
@fraenki ping :) here is the openssl package

https://pkg.opnsense.org/FreeBSD:11:amd64/17.7/next-open/All/haproxy-1.7.9.txz

**Comment by fraenki** [comment]
Will do a quick test tonight. :)

**Comment by fraenki** [comment]
Looks good to me, HAProxy 1.7.9 seems to work as expected.

**Comment by fichtner** [comment]
ok, let's ship it then.... thanks for testing :)
