### ISSUE TITLE
[clamd] bug in precompiled package

### ISSUE THREAD

**Issue by Stephanowicz** [opnsense/ports#47]
Hi,

there seems to be a bug in the precompiled clam-av package.
At least 1 person can confirm this --> [https://forum.opnsense.org/index.php?topic=6147.0](https://forum.opnsense.org/index.php?topic=6147.0)

I stumbled over this when downloading  [ http://downloads.music-group.com/software/behringer/X32/Behringer_XUF_USB_Drv_V6_13_0_arch_signed.zip](http://downloads.music-group.com/software/behringer/X32/Behringer_XUF_USB_Drv_V6_13_0_arch_signed.zip)
This crashed clamd with signal 11
I could reproduce this after a clean reboot and sometimes when restarting clamd.

Finally I installed the ports and recompiled and reinstalled clam-av - at moment I'm still observing this, but it seems that this fixed the problem.

Cheers, Stephan

**Comment by fichtner** [comment]
Stephan, did you use the freebsd or opnsense ports tree?

**Comment by Stephanowicz** [comment]
@fichtner I used the opsense port as You've described [here](https://forum.opnsense.org/index.php?topic=2004)

**Comment by fichtner** [comment]
that should make zero difference, except when the clamav build is pulling in machine-dependent assembler code...

**Comment by Stephanowicz** [comment]
I dunno^^
All I can say, that clamd crashed when scanning the mentioned file and after compiling it, it now seems to work... sry^^

**Comment by fichtner** [comment]
can you paste your first 20 lines of dmesg boot output for reference ? it's on the crash reporter page when you generate a report...

**Comment by Stephanowicz** [comment]
[dmesg.zip](https://github.com/opnsense/ports/files/1380195/dmesg.zip)

**Comment by Stephanowicz** [comment]
Ok - thought the whole file would be helpful^^
Maybe the config.log could be also helpful?
[config.zip](https://github.com/opnsense/ports/files/1380553/config.zip)
(I compiled it with debug enabled, as the guy from clamav.net suggested)

**Comment by fichtner** [comment]
we are about to ship 0.100.0, not sure if still the case... we can always reopen

**Comment by fichtner** [comment]
Hi Stephan,

When you are on 17.7.12_1 you can see the upgrade / EoL info box on the main firmware page where you would normally update. The process is therefor not documented, because it's the same mechanism.


Cheers,
Franco
