### ISSUE TITLE
zabbix32-proxy package request

### ISSUE THREAD

**Issue by ra1nb0w** [opnsense/ports#48]
I hope that this is the right place.
Unfortunately, zabbix-server and zabbix-proxy should be at the same version, in fact the proxy doesn't work if you use 3.4 version with server at 3.0. Can you package zabbix34-proxy and zabbix32-proxy?
With agent this doesn't happen.
thanks a lot

**Comment by fichtner** [comment]
I see your problem, but we would rather not keep multiple versions of zabbix in the binary packages.

You can build zabbix32-proxy from source anytime:

# opnsense-code tools ports
# cd /usr/ports/net-mgmt/zabbix32-proxy
# make install


Cheers,
Franco

**Comment by ra1nb0w** [comment]
thank for the answer.
I undestand your idea of cleanes but building "everytime" a single package is painful. And adding only one single package,besides manualy configured, could be done without any system/management impact. Anyway thanks for the hard work done on opnsense.

**Comment by fichtner** [comment]
Consider building many packages for each release, for all architectures, for each crypto flavour every other week, this is about 350 packages * 2 architectures * 2 crypto flavour * 25 times per year. Any deduplication here helps to push out timely releases, reduces attack surface, and reduces the potential to work around a non-working port update by upstream... If you are not using zabbix34-proxy, I'd even try to remove this as well, the courtesy of providing zabbix32-proxy made sense, but now it seems to add strain to the build for no reason :)


Cheers,
Franco

**Comment by ra1nb0w** [comment]
you are so kind. Yes, change zabbix34-proxy to zabbix32-proxy. Thanks ;-)

**Comment by fichtner** [comment]
I'm changing it back for 17.7 and hopefully nobody else will complain, but this will not carry over to 18.1.

**Comment by ra1nb0w** [comment]
ok. Thanks!

**Comment by fichtner** [comment]
sure :) see https://github.com/opnsense/tools/commit/0c5f61f58

**Comment by fichtner** [comment]
@ra1nb0w hey, @mimugmail is currently building a zabbix proxy plugin. we were discussing LTS version usage, would you mind if we downgrade to zabbix30-proxy?

**Comment by ra1nb0w** [comment]
yes, I already use that version on the server because LTS.
Would be great to have the gui plugin. thanks @mimugmail

**Comment by mimugmail** [comment]
@ra1nb0w 

Would this fit your needs or do you need more options?

![image](https://user-images.githubusercontent.com/20438689/31934320-0b25e690-b8ac-11e7-968a-64410d8a9ade.png)

**Comment by ra1nb0w** [comment]
nice :)
sometime, I also use UserParameter= so probably we can add a custom text box like unbound; what do you think?

**Comment by mimugmail** [comment]
UserParameter is for agents .. not proxy.

**Comment by ra1nb0w** [comment]
ops. sorry, you are right, wrong less file :(
ok for me

**Comment by hudecof** [comment]
@fichtner Im not BDS man, but need to compil ethe zabbix34-proxy with SQLLITE. What should be change Right now it compis with MYSQL;(
