### ISSUE TITLE
Undefined symbol "__safestack_unsafe_stack_ptr"

### ISSUE THREAD

**Issue by Stephanowicz** [opnsense/ports#49]
Hi,

I wanted to install nfdump and nfsen from the ports.

I got this error first when compiling nfdump. I finally managed to compile it with adding 
```
CFLAGS+= -fsanitize=safe-stack
CXXFLAGS+= -fsanitize=safe-stack
LDFLAGS+= -fsanitize=safe-stack

```
to the makefile.

But now I'm stuck with starting nfsen, as this error now occurs in the pearl loader:

> Can't load '/usr/local/lib/perl5/site_perl/mach/5.24/auto/RRDs/RRDs.so' for module RRDs: /usr/local/lib/librrd.so.8: Undefined symbol "__safestack_unsafe_stack_ptr" at /usr/local/lib/perl5/5.24/mach/DynaLoader.pm line 193.

Is there any workaround to get this running?

Cheers,

Stephan

**Comment by fichtner** [comment]
this was built with safestack, but safestack does not work on shared libraries very well

try to rebuild cleanly with

    # make your-command HARDENING_OFF=safestack

Find out which pkg uses the RRDs.so file by:

    # pkg which /usr/local/lib/perl5/site_perl/mach/5.24/auto/RRDs/RRDs.so

Remove the port, build again...

**Comment by Stephanowicz** [comment]
Great! That did it!

Thanx,

Stephan

**Comment by fichtner** [comment]
cool :) please leave this open, I need to fix hardenedbsd safestack annotations.

**Comment by fichtner** [comment]
Removed safestack from rrdtool in OPNsense ports repo (wasn't in HardenedBSD), thanks for the report!
