### ISSUE TITLE
bsdinstaller very slow on mmc/sd cards

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/ports#5]
When installing on a mmc device, this sometimes takes a very long time ( > 1hour).
The reason for this is that the target device is mounted without the async option, when adding "-o async" to the mount tag in usr/local/share/dfuibe_lua/conf/BSDInstaller.lua the problem is fixed.

Proposed fix: change the default setting for the installer to async.

**Comment by fichtner** [comment]
Yay, thanks for pointing that out! :)
