### ISSUE TITLE
freeradius3: Wrong owner for /var/run/radiusd

### ISSUE THREAD

**Issue by cdoenges** [opnsense/ports#50]
The directory /var/run/radiusd is created belonging to root:root. This causes an error while radiusd starts:

> Error: Failed creating PID file /var/run/radiusd/radiusd.pid: Permission denied

The command
`sudo chown freeradius:freeradius /var/run/radiusd`
fixes the issue.

I'm not sure where the command belongs. Does  [ports/net/freeradius3/pkg-plist](https://github.com/opnsense/ports/blob/master/net/freeradius3/pkg-plist) "know" the user after installation? If so, line 950 could be changed from

> @exec mkdir -p /var/run/radiusd

to

> @exec mkdir -p /var/run/radiusd; chown freeradius:freeradius /var/run/radiusd

If the user is defined elsewhere, the command belongs somewhere else ...

**Comment by fichtner** [comment]
@cdoenges Are you not using the plugin? As far as I can see we have fixed it over there:

https://github.com/opnsense/plugins/blob/master/net/freeradius/src/opnsense/scripts/Freeradius/setup.sh#L11

If the answer is no, it should rather be reported via https://bugs.freebsd.org/bugzilla/
