### ISSUE TITLE
ruby update

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/ports#52]
current stable release is 2.5

From the [release note](https://www.ruby-lang.org/de/news/2017/12/25/ruby-2-5-0-released/) it looks like it got faster and more regex features.

**Comment by fichtner** [comment]
This is a tools ticket, but let’s leave it here. I will switch 18.1 ruby to 2.5 :)

**Comment by fabianfrz** [comment]
@fichtner upps, sorry for the second ticket. It looks like 2.5 is not in the upstream repository.

**Comment by fichtner** [comment]
Looks like this should do it... https://github.com/opnsense/tools/commit/858a419a2d4f69ca2b94c585acfbfea19f9ec2cd

**Comment by fabianfrz** [comment]
👍
