### ISSUE TITLE
Ansible ports package

### ISSUE THREAD

**Issue by jschellevis** [opnsense/ports#53]
@fichtner please add sysutils/ansible to the standard build.

"Ansible is a simple automation language that can perfectly describe an IT application infrastructure. It’s easy-to-learn, self-documenting, and doesn’t require a grad-level computer science degree to read. Automation shouldn’t be more complex than the tasks it’s replacing." - quote from the Ansible website for reference what this package does.

I will need this for a few projects.

**Comment by fichtner** [comment]
Done.
