### ISSUE TITLE
dhcp6c re-read config on SIGUP

### ISSUE THREAD

**Issue by marjohn56** [opnsense/ports#54]
I have made a change to force dhcp6c to re-read the config on SIGUP. Do we want to post this upstream where it may sit for a very long time, or just update the port here?

The new version also contains the RAW parameters features.

**Comment by fichtner** [comment]
if the patches are manageable we add them to the ports, if not we may as well fork dhcp6c and add our own port?

**Comment by marjohn56** [comment]
I'll post the patches shortly and let the master make that decision. :)

**Comment by fichtner** [comment]
Merged and live in 18.1.7.

**Comment by marjohn56** [comment]
Nice..

Greetings from Belize. :)

**Comment by fichtner** [comment]
Hello Sir, best greetings and enjoy! :)
