### ISSUE TITLE
nginx won't start after reboot missing /var/log/nginx

### ISSUE THREAD

**Issue by jodumont** [opnsense/ports#59]
Hi;

I install nginx and made is /etc/rc.conf.d/nginx file
but on every reboot I need to recreate the /**var/log/nginx** unless nginx complain

> root@OPNsense:~ # service -R nginx
> nginx not running? (check /var/run/nginx.pid).
> Stopping redis.
> Waiting for PIDS: 21436.
> Starting redis.
> Performing sanity check on nginx configuration:
> nginx: [alert] could not open error log file: open() "**/var/log/nginx/**error.log" failed (2: No such file or directory)
> nginx: the configuration file /usr/local/etc/nginx/nginx.conf syntax is ok
> 2018/03/30 16:10:32 [emerg] 16576#100125: open() "**/var/log/nginx/**access.log" failed (2: No such file or directory)
> nginx: configuration file /usr/local/etc/nginx/nginx.conf test failed
> Starting nginx.
> nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (2: No such file or directory)
> 2018/03/30 16:10:32 [emerg] 16601#100125: open() "/var/log/nginx/access.log" failed (2: No such file or directory)
> /usr/sbin/service: WARNING: failed to start nginx

There is a way to make this var/log/nginx persistent over reboot ?

Regards!

Jonathan
there is a way to make permanent change like this ?

**Comment by fichtner** [comment]
Hi there,

You probably have /var MFS enabled under System: Settings: Misc. Disabling will work....

Best scenario here for compatibility is to build a plugin wrapper, we usually solve this via a dedicated „setup.sh“ during boot for plugins that need special /var directories.

But there is no Nginx plugin yet.


Cheers,
Franco

**Comment by fabianfrz** [comment]
a quick and dirty fix would be changing the path to `/var/log/LOGFILE` so the directory is not needed.

**Comment by jodumont** [comment]
@fichtner yes I just realize that ;)
via df ;)

sorry
