### ISSUE TITLE
Cant compile GetDNS

### ISSUE THREAD

**Issue by nekromantik** [opnsense/ports#63]
Hi all
Did a fresh install of OPNSense 18.7 and did update to 18.7.9 via GUI.
Now I followed guide previously used on opnsense forums to build getdns with stubby.
However I cannot compile it any more.
I get the following error:

`
*** Configure:  Fatal Error:  /usr/sbin/dtrace doesn't support -h flag
***
*** Your installed dtrace doesn't support the -h switch to compile a D
*** program into a C header. Can't continue.

===>  Script "Configure" failed unexpectedly.
Please report the problem to mat@FreeBSD.org [maintainer] and attach the
"/usr/obj/usr/ports/lang/perl5.28/work/perl-5.28.1/config.log" including the
output of the failure of your make command. Also, it might be a good idea to
provide an overview of all packages installed on your system (e.g. a
/usr/local/sbin/pkg-static info -g -Ea).
*** Error code 1

Stop.
make[4]: stopped in /usr/ports/lang/perl5.28
*** Error code 1

Stop.
make[3]: stopped in /usr/ports/misc/help2man
*** Error code 1

Stop.
make[2]: stopped in /usr/ports/print/texinfo
*** Error code 1

Stop.
make[1]: stopped in /usr/ports/dns/libidn
*** Error code 1

Stop.
`

**Comment by fichtner** [comment]
Not sure what's wrong, but in any case you should use our official package now:

    # pkg install getdns


Cheers,
Franco

**Comment by nekromantik** [comment]
oh I will use that then. thanks! no one updated the post on opnsense forums

**Comment by fichtner** [comment]
there were several threads unfortunately... it's a bit confusing. if you can please update your forum question too :)


Thanks,
Franco
