### ISSUE TITLE
security/acme.sh: update to 2.8.0

### ISSUE THREAD

**Issue by fraenki** [opnsense/ports#64]
Version 2.8.0 was finally released:
https://github.com/Neilpang/acme.sh/releases/tag/2.8.0

It's been 6+ months since the last release, so it's probably a good idea to test it. I'll do once it's merged and packaged :)

**Comment by fichtner** [comment]
I will ping the maintainer

**Comment by fraenki** [comment]
I've submitted an update for the FreeBSD port:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=236041

@fichtner, if the patch does not get merged in-time for the next release I'd suggest to merge it manually.

**Comment by fichtner** [comment]
@fraenki https://github.com/opnsense/ports/commit/9a918db5af5 done, thanks!
