### ISSUE TITLE
Document use of % in syslogd manpage

### ISSUE THREAD

**Issue by beren12** [opnsense/ports#65]
Looks like syslog has extra magic to support clog, please document it as it's used nowhere else on the internet.

https://github.com/opnsense/ports/blob/master/opnsense/syslogd/files/extra-clog-support.diff#L111

**Comment by fichtner** [comment]
https://github.com/opnsense/core/issues/5337 is on the roadmap for 22.1 so this is no longer required as the port is going to be removed.
