### ISSUE TITLE
www/phalcon: add support for aarch64

### ISSUE THREAD

**Issue by nekoprog** [opnsense/ports#67]
Hello, I got an error while running `make distfiles` for aarch64, it says:
> ===> php71-phalcon-3.4.3 is only for amd64 armv6 armv7 i386, while you are running aarch64.

Hope that you can add aarch64 support into Ports.

**Comment by fichtner** [comment]
I'll take this to https://bugs.freebsd.org/bugzilla/ -- are you sure it compiles ok?

**Comment by nekoprog** [comment]
Other packages before that line compiles successfully, maybe limitation on Makefile, I'm not diving it that yet.

**Comment by fichtner** [comment]
It's restricted in the port, but it can be enabled quite easily if it works.

**Comment by nekoprog** [comment]
I could try running `make distfiles` again if you can allow all packages on port for aarch64.

**Comment by fichtner** [comment]
Try https://github.com/opnsense/ports/commit/08b945e8eb -- cannot test at the moment -- maybe there's a typo in PBITS setting

**Comment by nekoprog** [comment]
Thanks, I will report the result soon.

**Comment by nekoprog** [comment]
@fichtner Hello, distfiles successfully built.
`>>> Creating distfiles set... done`
`# ls /usr/local/opnsense/build/19.1/aarch64/sets`
`distfiles-19.1.4_75.tar`

**Comment by fichtner** [comment]
@nekoprog distfile fix is trivial, I'm not sure about ports build just yet...

**Comment by nekoprog** [comment]
I'll run `make packages` later, will reopen this issue if had a problem.

**Comment by fichtner** [comment]
ok, thanks ❤️

**Comment by fichtner** [comment]
Sorry, small typo here https://github.com/opnsense/ports/commit/62efb3bf3e1
