### ISSUE TITLE
pfctl: opnsense driver does not support altq

### ISSUE THREAD

**Issue by lukepower** [opnsense/ports#7]
I installed today Opnsense and all went smooth (well, mostly).
When I went on and set up Traffic Shaping, i get these messages as notifications:
 [ There were error(s) loading the rules: pfctl: em2_vlan20: driver does not support altq - The line in question reads [0]: ]

Yes, I am using VLANs so it might actually be a driver problem. I dug through some forum entries at pfSense, and it seems that there were some patches they applied to fix some NIC drivers, but they reverted back to non-working at some point during 2.2 development...

**Comment by fichtner** [comment]
Duplicated by https://github.com/opnsense/core/issues/97 -- has better error message.
