### ISSUE TITLE
miniupnpd upstream sync issue

### ISSUE THREAD

**Issue by azdps** [opnsense/ports#72]
fichtner you attempted to sync miniupnpd with upstream on April 2nd with commit [50d8ecd](https://github.com/opnsense/ports/commit/50d8ecda62e931d1ada72e335a122f30820f9017) and then reverted it. The problem with this upstream sync was that it introduced the new patch file patch-portinuse.c. This new patch was intended for FreeBSD 12+ for port miniupnpd-2.1.20190210. The patch was not meant to be used on FreeBSD 11.2 and the build will fail if the patch is present. Build the port without the patch-portinuse.c file and miniupnpd with build and run correctly. Also option CHECK_PORTINUSE should be set to yes since I don't think it is in upstream HardenedBSD from my testing.

Thanks

**Comment by fichtner** [comment]
Hi @azdps,

Thanks for the analysis! ❤️ 

At the time I had no time to look into it further so I did a revert.

I've made some noise in FreeBSD where the 11.x breakage stems from... We have CHECK_PORTINUSE on and the miniupnpd code is synced with commit https://github.com/opnsense/ports/commit/579255ee16 and will be shipped in 19.1.8.


Cheers,
Franco
