### ISSUE TITLE
net/haproxy: sync with upstream (2.0.4)

### ISSUE THREAD

**Issue by fraenki** [opnsense/ports#73]
Hi @fichtner,

please sync net/haproxy with upstream so that we can test HAProxy 2.0 with the development version. Thanks :)

refs https://github.com/opnsense/plugins/issues/1089

**Comment by fichtner** [comment]
Will be done after 19.7.2 is out. Can't cope with LibreSSL breakage at the moment.

**Comment by fichtner** [comment]
https://github.com/opnsense/ports/commit/3670ece8c4ea7b568346cb6c41d066757750626f
https://github.com/opnsense/ports/commit/a8b7383a2203ec959cdce35a8dd5d7effaf2264f
