### ISSUE TITLE
Request to integrate radvd 2.18 to address IPv6 routing needs

### ISSUE THREAD

**Issue by unquietwiki** [opnsense/ports#76]
* https://github.com/opnsense/ports/tree/master/net/radvd
* http://www.litech.org/radvd/

OPNsense 19.7.3 is still using an old version of radvd; and the synced FreeBSD port was last updated 5 months ago with radvd 2.18. I'm having trouble with routing advertisements in my environment, but can't test this as a resolution, since https://forum.opnsense.org/index.php?topic=2161.0 doesn't permit someone to overwrite the radvd1-1.15 package. Thank you.

**Comment by fichtner** [comment]
Hi @unquietwiki,

The system does permit, but not in easy ways to prevent foot shooting. I've never gotten radvd 2 to work in my IPv6 environments where radvd 1 would always work.

That being said wait for 19.7.4 and then report back to figure out a way to install radvd in your environment together. The update is scheduled for next week. :)


Cheers,
Franco

**Comment by unquietwiki** [comment]
@fichtner Thanks for the quick reply! I'd be happy to help troubleshoot an updated package if installing it is possible. Just let me know!

**Comment by unquietwiki** [comment]
@fichtner I figured out my site routing issure: IGMP switch interference. However, I am still interested in testing the newer radvd. Thanks!

**Comment by fichtner** [comment]
@unquietwiki ok, glad to hear. As I said just ping me when 19.7.4 is out as it's difficult to keep track of GitHub tickets due date wise :)

**Comment by unquietwiki** [comment]
@fichtner Hey Franco. I saw 19.7.4 was out, and that you had added something to try to make radvd work. It still won't install the pkg/port without wanting to uninstall OPNsense; even tried portmaster & all that did was upgrade nano.

```
/usr/ports/net/radvd # pkg install radvd
Updating OPNsense repository catalogue...
OPNsense repository is up to date.
All repositories are up to date.
Checking integrity... done (1 conflicting)
  - radvd-2.18 conflicts with radvd1-1.15 on /usr/local/etc/rc.d/radvd
Checking integrity... done (0 conflicting)
The following 4 package(s) will be affected (of 0 checked):

Installed packages to be REMOVED:
        radvd1-1.15
        opnsense-19.7.4

New packages to be INSTALLED:
        radvd: 2.18

Installed packages to be REINSTALLED:
        pkg-1.10.5_5

Number of packages to be removed: 2
Number of packages to be installed: 1
Number of packages to be reinstalled: 1

```

**Comment by fichtner** [comment]
@unquietwiki that's expected. Make sure you are on 19.7.4 and then do the following from the root shell:

# opnsense-code core
# cd /usr/core
# git checkout stable/19.7
# make upgrade CORE_RADVD=


Cheers,
Franco

**Comment by unquietwiki** [comment]
@fichtner Thanks for the quick response! I've done the following; maybe this meets your criteria...

- Followed your instructions to migrate to the 19.7.x branch, with the new radvd.
- Verified radvd is version 2.18
- Restarted, stopped, and started the service successfully.
- Rebooted a Win10 box & successfully had it get DHCPv6 & stateless-autoconfig addresses.

Anything more you want me to do on my end?

**Comment by fichtner** [comment]
Hey @unquietwiki,

Finally got around to poking at the issue. 20.1.4 will include radvd 2 package with 0272bee which seems to address the issues for me and makes this workable. If you have some time to confirm that would be great.  :)


Cheers,
Franco

**Comment by unquietwiki** [comment]
Thanks for the update! I'm not at the job any more with that install; I can
put you in touch with my replacement, or we can put out a call for help on
Reddit. My own home environment is OpenWRT-based, else I'd test it here.

**Comment by fichtner** [comment]
@unquietwiki no worries, we'll likely pull it into the development version soon and see what happens as confidence in the fix is pretty high. I'm closing this ticket then and thanks for the help!

**Comment by unquietwiki** [comment]
No problem! 👍
