### ISSUE TITLE
Multicast relay - port addition

### ISSUE THREAD

**Issue by marjohn56** [opnsense/ports#83]
We've been playing around for a couple of weeks looking for something that will relay both Sonos and Sky Q SSDP packets reliably between interfaces, it appears we have found the beast. The program is very simple and appears to work flawlessly.

Any chance of adding this to the ports?

https://github.com/sonicsnes/udp-broadcast-relay-redux

Wrong area.. should be in src!

**Comment by marjohn56** [comment]
Bump..

I have an updated version of this now, it generates its own PIDs making it much more friendly when running multiple instances, the plugin is now also ready. Where do you want me to PR the this too. Once its pulled in I'll PR the plugin.

**Comment by fichtner** [comment]
well, this should be ports... is this the definitive upstream? it looks like its a fork

**Comment by marjohn56** [comment]
No, it's in ports...

**Comment by marjohn56** [comment]
Sorry.. clicked wrong button. It doesn't exist upstream. We found it, played with it, liked it, modified it and decided we should use it. :)

**Comment by marjohn56** [comment]
I have an updated Readme.md & Contributors file to push when I get 10 minutes. Berto did a lot of work on it.
